### ISSUE TITLE
Keyholder auf status anzeigen

### ISSUE THREAD

**Issue by sre** [ktt-ol/spacestatus2#1]
Hi,

Es wäre cool, wenn auf status auch der aktuelle Keyholder angezeigt wird.

-- Sebastian

**Comment by thedm** [comment]
Wurde Anscheinend in dd6f59d627ab27ae245901d0fcfb99d9602c3765 hinzugefügt

-- Domse

**Comment by smilix** [comment]
Sehe ich auch so
